version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
      image: postgres:latest
      environment:
        POSTGRES_USER: alinauser
        POSTGRES_PASSWORD: 1356
        POSTGRES_DB: alinadatabase
      ports:
        - "5432:5432"
      restart: unless-stopped